// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ProtoID int32

const (
	ProtoID_SyncWorker      ProtoID = 0
	ProtoID_ConsensusWorker ProtoID = 1
)

var ProtoID_name = map[int32]string{
	0: "SyncWorker",
	1: "ConsensusWorker",
}
var ProtoID_value = map[string]int32{
	"SyncWorker":      0,
	"ConsensusWorker": 1,
}

func (x ProtoID) String() string {
	return proto1.EnumName(ProtoID_name, int32(x))
}
func (ProtoID) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type MsgType int32

const (
	MsgType_BC_GetBlocksMsg     MsgType = 0
	MsgType_BC_GetInvMsg        MsgType = 1
	MsgType_BC_GetDataMsg       MsgType = 2
	MsgType_BC_OnBlockMsg       MsgType = 3
	MsgType_BC_OnTransactionMsg MsgType = 4
	MsgType_BC_OnStatusMSg      MsgType = 5
)

var MsgType_name = map[int32]string{
	0: "BC_GetBlocksMsg",
	1: "BC_GetInvMsg",
	2: "BC_GetDataMsg",
	3: "BC_OnBlockMsg",
	4: "BC_OnTransactionMsg",
	5: "BC_OnStatusMSg",
}
var MsgType_value = map[string]int32{
	"BC_GetBlocksMsg":     0,
	"BC_GetInvMsg":        1,
	"BC_GetDataMsg":       2,
	"BC_OnBlockMsg":       3,
	"BC_OnTransactionMsg": 4,
	"BC_OnStatusMSg":      5,
}

func (x MsgType) String() string {
	return proto1.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type InvType int32

const (
	InvType_block       InvType = 0
	InvType_transaction InvType = 1
)

var InvType_name = map[int32]string{
	0: "block",
	1: "transaction",
}
var InvType_value = map[string]int32{
	"block":       0,
	"transaction": 1,
}

func (x InvType) String() string {
	return proto1.EnumName(InvType_name, int32(x))
}
func (InvType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type GetBlocksMsg struct {
	Version       uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	LocatorHashes []string `protobuf:"bytes,2,rep,name=locatorHashes" json:"locatorHashes,omitempty"`
	HashStop      string   `protobuf:"bytes,3,opt,name=hashStop" json:"hashStop,omitempty"`
}

func (m *GetBlocksMsg) Reset()                    { *m = GetBlocksMsg{} }
func (m *GetBlocksMsg) String() string            { return proto1.CompactTextString(m) }
func (*GetBlocksMsg) ProtoMessage()               {}
func (*GetBlocksMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GetBlocksMsg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetBlocksMsg) GetLocatorHashes() []string {
	if m != nil {
		return m.LocatorHashes
	}
	return nil
}

func (m *GetBlocksMsg) GetHashStop() string {
	if m != nil {
		return m.HashStop
	}
	return ""
}

type StatusMsg struct {
	Version     uint32 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	StartHeight uint32 `protobuf:"varint,2,opt,name=StartHeight" json:"StartHeight,omitempty"`
}

func (m *StatusMsg) Reset()                    { *m = StatusMsg{} }
func (m *StatusMsg) String() string            { return proto1.CompactTextString(m) }
func (*StatusMsg) ProtoMessage()               {}
func (*StatusMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *StatusMsg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *StatusMsg) GetStartHeight() uint32 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

type GetInvMsg struct {
	Type  InvType  `protobuf:"varint,1,opt,name=type,enum=proto.InvType" json:"type,omitempty"`
	Hashs []string `protobuf:"bytes,2,rep,name=hashs" json:"hashs,omitempty"`
}

func (m *GetInvMsg) Reset()                    { *m = GetInvMsg{} }
func (m *GetInvMsg) String() string            { return proto1.CompactTextString(m) }
func (*GetInvMsg) ProtoMessage()               {}
func (*GetInvMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetInvMsg) GetType() InvType {
	if m != nil {
		return m.Type
	}
	return InvType_block
}

func (m *GetInvMsg) GetHashs() []string {
	if m != nil {
		return m.Hashs
	}
	return nil
}

type OnBlockMsg struct {
	Block *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *OnBlockMsg) Reset()                    { *m = OnBlockMsg{} }
func (m *OnBlockMsg) String() string            { return proto1.CompactTextString(m) }
func (*OnBlockMsg) ProtoMessage()               {}
func (*OnBlockMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *OnBlockMsg) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type OnTransactionMsg struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
}

func (m *OnTransactionMsg) Reset()                    { *m = OnTransactionMsg{} }
func (m *OnTransactionMsg) String() string            { return proto1.CompactTextString(m) }
func (*OnTransactionMsg) ProtoMessage()               {}
func (*OnTransactionMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *OnTransactionMsg) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type GetDataMsg struct {
	InvList []*GetInvMsg `protobuf:"bytes,1,rep,name=InvList" json:"InvList,omitempty"`
}

func (m *GetDataMsg) Reset()                    { *m = GetDataMsg{} }
func (m *GetDataMsg) String() string            { return proto1.CompactTextString(m) }
func (*GetDataMsg) ProtoMessage()               {}
func (*GetDataMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GetDataMsg) GetInvList() []*GetInvMsg {
	if m != nil {
		return m.InvList
	}
	return nil
}

func init() {
	proto1.RegisterType((*GetBlocksMsg)(nil), "proto.GetBlocksMsg")
	proto1.RegisterType((*StatusMsg)(nil), "proto.StatusMsg")
	proto1.RegisterType((*GetInvMsg)(nil), "proto.GetInvMsg")
	proto1.RegisterType((*OnBlockMsg)(nil), "proto.OnBlockMsg")
	proto1.RegisterType((*OnTransactionMsg)(nil), "proto.OnTransactionMsg")
	proto1.RegisterType((*GetDataMsg)(nil), "proto.GetDataMsg")
	proto1.RegisterEnum("proto.ProtoID", ProtoID_name, ProtoID_value)
	proto1.RegisterEnum("proto.MsgType", MsgType_name, MsgType_value)
	proto1.RegisterEnum("proto.InvType", InvType_name, InvType_value)
}

func init() { proto1.RegisterFile("message.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xf5, 0xda, 0x71, 0x5d, 0x8d, 0x6c, 0x67, 0xb3, 0x29, 0x54, 0xf8, 0x24, 0x44, 0x0b, 0xc6,
	0x07, 0x53, 0xdc, 0x1e, 0x7a, 0x4e, 0x52, 0x6c, 0x43, 0x43, 0x8a, 0x14, 0xda, 0x63, 0xd9, 0x88,
	0x45, 0x52, 0x93, 0xee, 0x0a, 0xed, 0x44, 0xe0, 0x73, 0xff, 0x78, 0xd9, 0x0f, 0x25, 0xd2, 0x69,
	0x99, 0xf7, 0x66, 0xde, 0xcc, 0x7b, 0x0b, 0x8b, 0xbf, 0x42, 0x6b, 0x5e, 0x88, 0x6d, 0xdd, 0x28,
	0x54, 0x6c, 0x6a, 0x9f, 0x55, 0xf8, 0xf0, 0xa4, 0xf2, 0x47, 0x87, 0xad, 0x2e, 0xb0, 0xe1, 0x52,
	0xf3, 0x1c, 0x2b, 0x25, 0x1d, 0x94, 0xfc, 0x81, 0xf9, 0x5e, 0xe0, 0x95, 0x69, 0xd2, 0xb7, 0xba,
	0x60, 0x11, 0xcc, 0x5a, 0xd1, 0xe8, 0x4a, 0xc9, 0x88, 0xc4, 0x64, 0xbd, 0x48, 0xbb, 0x92, 0x7d,
	0x80, 0xc5, 0x93, 0xca, 0x39, 0xaa, 0xe6, 0xc0, 0x75, 0x29, 0x74, 0x34, 0x8e, 0x27, 0xeb, 0x20,
	0x1d, 0x82, 0x6c, 0x05, 0x6f, 0x4b, 0xae, 0xcb, 0x0c, 0x55, 0x1d, 0x4d, 0x62, 0xb2, 0x0e, 0xd2,
	0x97, 0x3a, 0xd9, 0x43, 0x90, 0x21, 0xc7, 0xe7, 0x6e, 0xd1, 0xcf, 0xe1, 0x22, 0x5f, 0xb2, 0x18,
	0xc2, 0x0c, 0x79, 0x83, 0x07, 0x51, 0x15, 0x25, 0x46, 0x63, 0xcb, 0xf6, 0xa1, 0xe4, 0x1b, 0x04,
	0x7b, 0x81, 0x47, 0xd9, 0x1a, 0xa1, 0x04, 0xce, 0xf0, 0x54, 0x0b, 0xab, 0xb2, 0xdc, 0x2d, 0x9d,
	0xaf, 0xed, 0x51, 0xb6, 0xf7, 0xa7, 0x5a, 0xa4, 0x96, 0x63, 0xef, 0x60, 0x6a, 0xae, 0xe8, 0x6e,
	0x76, 0x45, 0xf2, 0x09, 0xe0, 0x4e, 0x5a, 0xeb, 0x4e, 0x67, 0x6a, 0xb3, 0xb2, 0x42, 0xe1, 0x6e,
	0xee, 0x85, 0x2c, 0x9f, 0x3a, 0x2a, 0x39, 0x00, 0xbd, 0x93, 0xf7, 0xaf, 0x21, 0x9a, 0xb9, 0x2f,
	0x10, 0xf6, 0x62, 0xf5, 0xd3, 0xcc, 0x4f, 0xf7, 0x7a, 0xd3, 0x7e, 0x5b, 0xf2, 0x15, 0x60, 0x2f,
	0xf0, 0x86, 0x23, 0x37, 0x1a, 0x1b, 0x98, 0x1d, 0x65, 0xfb, 0xbd, 0xd2, 0x18, 0x91, 0x78, 0xb2,
	0x0e, 0x77, 0xd4, 0xcf, 0xbf, 0xd8, 0x4c, 0xbb, 0x86, 0xcd, 0x16, 0x66, 0x3f, 0x0c, 0x77, 0xbc,
	0x61, 0x4b, 0x80, 0xec, 0x24, 0xf3, 0x5f, 0xaa, 0x79, 0x14, 0x0d, 0x1d, 0xb1, 0x4b, 0x38, 0xbf,
	0x56, 0x52, 0x0b, 0xa9, 0x9f, 0xb5, 0x07, 0xc9, 0xe6, 0x1f, 0x81, 0xd9, 0xad, 0x2e, 0x4c, 0x1a,
	0xa6, 0xe1, 0xea, 0xfa, 0x77, 0xff, 0xc3, 0xe9, 0x88, 0x51, 0x98, 0x3b, 0xd0, 0x6d, 0xa2, 0x84,
	0x5d, 0xc0, 0xc2, 0x21, 0xfe, 0x3e, 0x3a, 0xf6, 0xd0, 0x6b, 0x5c, 0x74, 0xc2, 0xde, 0xc3, 0xa5,
	0x85, 0x86, 0x79, 0xd0, 0x33, 0xc6, 0x60, 0x69, 0x09, 0xff, 0xd9, 0x59, 0x41, 0xa7, 0x9b, 0x8f,
	0xd6, 0xa1, 0x3d, 0x22, 0xf0, 0x41, 0xd3, 0x11, 0x3b, 0x1f, 0x64, 0x47, 0xc9, 0xc3, 0x1b, 0x6b,
	0xfb, 0xf3, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x5a, 0xc8, 0x78, 0xcd, 0x02, 0x00, 0x00,
}
